
GET https://nqzspty8wf.execute-api.eu-north-1.amazonaws.com/prod/spaces
###

POST https://nqzspty8wf.execute-api.eu-north-1.amazonaws.com/prod/spaces
content-type: application/json

{
  "location": "Helsinki",
  "name": "puge",
}
###

PUT https://nqzspty8wf.execute-api.eu-north-1.amazonaws.com/prod/spaces?id=5d8b494f
content-type: application/json

{
  "location": "Helsinki2"
}
###